parse_config:
  raw_binding_map:
    '&td_lb': {t: '(  <', h: '{ ['}
    '&td_rb': {t: ')  >', h: '} ]'}
  zmk_keycode_map:
    LG(N): Fndr
    LA(UP): Expose
    LA(LEFT): Page-L
    LA(RIGHT): Page-R
    LC(UP): 🚀
    LC(DOWN): Apps
    LG(LS(N3)): 📷
    # LG(MINUS): Zoom Out
    LA(LG(MINUS)): Zoom --
    LA(LG(EQUAL)): Zoom ++
    F10: 🔇
    F11: 🔉
    F12: 🔊
    F7: ⏪
    F8: ⏯️
    F9: ⏩
    LA(LC(SPACE)): 🌐
    AMPERSAND: '&'
    AMPS: '&'
    APOS: .
    APOSTROPHE: <
    ASTERISK: '*'
    ASTRK: '*'
    AT: '@'
    AT_SIGN: '@'
    BACKSLASH: \
    BSLH: \
    CARET: ^
    COLON: ':'
    COMMA: ','
    DLLR: $
    DOLLAR: $
    DOT: .
    DOUBLE_QUOTES: '"'
    DQT: '"'
    EQUAL: '='
    EXCL: '!'
    EXCLAMATION: '!'
    FSLH: /
    GRAVE: '`'
    GREATER_THAN: '>'
    GT: '>'
    HASH: '#'
    LBKT: '['
    LBRC: '{'
    LEFT_BRACE: '{'
    LEFT_BRACKET: '['
    LEFT_PARENTHESIS: (
    LESS_THAN: <
    LPAR: (
    LT: <
    MINUS: '-'
    NON_US_BACKSLASH: \
    NON_US_BSLH: '|'
    NON_US_HASH: '#'
    NUHS: '#'
    PERCENT: '%'
    PERIOD: .
    PIPE: '|'
    PIPE2: '|'
    PLUS: +
    POUND: '#'
    PRCNT: '%'
    QMARK: '?'
    QUESTION: '?'
    RBKT: ']'
    RBRC: '}'
    RIGHT_BRACE: '}'
    RIGHT_BRACKET: ']'
    RIGHT_PARENTHESIS: )
    RPAR: )
    SEMI: ;
    SEMICOLON: ;
    SINGLE_QUOTE: ''''
    SLASH: /
    SQT: ''''
    STAR: '*'
    TILDE: '~'
    TILDE2: '~'
    UNDER: _
    UNDERSCORE: _

error building: Run west update
  west update
  shell: sh -e {0}
  env:
    extra_cmake_args: -DSHIELD="corne_nice_view_left nice_view_adapter nice_view"
    artifact_name: corne_nice_view_left-nice_nano_v2-zmk
    display_name: corne_nice_view_left - nice_nano_v2
    zephyr_version: 3.2.0